package session

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/andreygrehov/range/internal/tool"
)

func TestParseLDCacheKeepsThisArchitecture(t *testing.T) {
	out := `1234 libs found in cache ` + "`/etc/ld.so.cache'" + `
	libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so.1 (libc6) => /usr/lib/i386-linux-gnu/libcuda.so.1
	libnvidia-ml.so.1 (libc6,AArch64) => /usr/lib/aarch64-linux-gnu/libnvidia-ml.so.1
	libc.so.6 (libc6,x86-64, OS ABI: Linux 3.2.0) => /lib/x86_64-linux-gnu/libc.so.6
Cache generated by: ldconfig (Ubuntu GLIBC 2.39) stable release version 2.39
`
	got := parseLDCache(out, "amd64")
	want := map[string]string{
		"libcuda.so.1": "/usr/lib/x86_64-linux-gnu/libcuda.so.1",
		"libc.so.6":    "/lib/x86_64-linux-gnu/libc.so.6",
	}
	if fmt.Sprint(got) != fmt.Sprint(want) {
		t.Errorf("amd64: got %v, want %v", got, want)
	}
	if got := parseLDCache(out, "arm64"); len(got) != 1 || got["libnvidia-ml.so.1"] == "" {
		t.Errorf("arm64: got %v", got)
	}
}

// fakeDriver lays out what an installed driver leaves on a host: device
// nodes, and libraries as their versioned files with soname links.
func fakeDriver(t *testing.T) (dev string, libraries map[string]string) {
	t.Helper()
	dir := t.TempDir()
	dev, lib := filepath.Join(dir, "dev"), filepath.Join(dir, "lib")
	for _, d := range []string{dev, lib} {
		if err := os.Mkdir(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	for _, node := range []string{"nvidia0", "nvidia1", "nvidiactl", "nvidia-uvm", "nvidia-caps"} {
		if err := os.WriteFile(filepath.Join(dev, node), nil, 0o666); err != nil {
			t.Fatal(err)
		}
	}
	libraries = map[string]string{}
	for _, name := range []string{"libcuda.so", "libnvidia-ml.so", "libGL.so", "libnvidia-mlx.so"} {
		file := filepath.Join(lib, name+".580.95.05")
		if err := os.WriteFile(file, []byte(name), 0o755); err != nil {
			t.Fatal(err)
		}
		link := filepath.Join(lib, name+".1")
		if err := os.Symlink(filepath.Base(file), link); err != nil {
			t.Fatal(err)
		}
		libraries[name+".1"] = link
	}
	return dev, libraries
}

func TestFindNVIDIA(t *testing.T) {
	dev, libraries := fakeDriver(t)
	lookPath := func(name string) (string, error) {
		if name == "nvidia-smi" {
			return "/usr/bin/nvidia-smi", nil
		}
		return "", errors.New("not found")
	}
	d, err := findNVIDIA(dev, libraries, lookPath)
	if err != nil {
		t.Fatal(err)
	}
	var devices []string
	for _, path := range d.Devices {
		devices = append(devices, filepath.Base(path))
	}
	if got := strings.Join(devices, " "); got != "nvidia-uvm nvidia0 nvidia1 nvidiactl" {
		t.Errorf("devices = %s", got)
	}
	if d.GPUs != 2 || d.Version != "580.95.05" {
		t.Errorf("GPUs = %d, version = %q", d.GPUs, d.Version)
	}
	// Only the driver's own libraries, with libcuda.so for programs that
	// open it by its plain name.
	if len(d.Files) != 2 || d.Files["libcuda.so.580.95.05"] == "" || d.Files["libnvidia-ml.so.580.95.05"] == "" {
		t.Errorf("files = %v", d.Files)
	}
	want := map[string]string{
		"libcuda.so": "libcuda.so.580.95.05", "libcuda.so.1": "libcuda.so.580.95.05",
		"libnvidia-ml.so.1": "libnvidia-ml.so.580.95.05",
	}
	if fmt.Sprint(d.Links) != fmt.Sprint(want) {
		t.Errorf("links = %v, want %v", d.Links, want)
	}
	if fmt.Sprint(d.Tools) != "[/usr/bin/nvidia-smi]" {
		t.Errorf("tools = %v", d.Tools)
	}
}

func TestFindNVIDIASaysWhatIsMissing(t *testing.T) {
	none := func(string) (string, error) { return "", errors.New("not found") }
	if _, err := findNVIDIA(t.TempDir(), nil, none); err == nil || !strings.Contains(err.Error(), "no NVIDIA driver") {
		t.Errorf("no driver: %v", err)
	}
	dev, libraries := fakeDriver(t)
	os.Remove(filepath.Join(dev, "nvidia-uvm"))
	if _, err := findNVIDIA(dev, libraries, none); err == nil || !strings.Contains(err.Error(), "nvidia-uvm") {
		t.Errorf("no nvidia-uvm: %v", err)
	}
	dev, _ = fakeDriver(t)
	if _, err := findNVIDIA(dev, nil, none); err == nil || !strings.Contains(err.Error(), "libcuda.so.1") {
		t.Errorf("no libcuda: %v", err)
	}
}

func TestWithNVIDIAEnv(t *testing.T) {
	cache := []string{"CUDA_CACHE_PATH=/usr/local/nvidia/cache", "CUDA_CACHE_MAXSIZE=4294967296"}
	cases := map[string][]string{
		"PATH=/bin LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/nvidia/lib": append([]string{
			"PATH=/bin:/usr/local/nvidia/bin", "LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/nvidia/lib"}, cache...),
		"PATH=/bin: LD_LIBRARY_PATH=": append([]string{
			"PATH=/bin:/usr/local/nvidia/bin", "LD_LIBRARY_PATH=/usr/local/nvidia/lib64"}, cache...),
		"HOME=/root PATH=/bin": append([]string{
			"HOME=/root", "PATH=/bin:/usr/local/nvidia/bin", "LD_LIBRARY_PATH=/usr/local/nvidia/lib64"}, cache...),
		// The image's or the user's own cache settings stand.
		"PATH=/bin LD_LIBRARY_PATH=/l CUDA_CACHE_PATH=/mine": {"PATH=/bin:/usr/local/nvidia/bin",
			"LD_LIBRARY_PATH=/l:/usr/local/nvidia/lib64", "CUDA_CACHE_PATH=/mine", "CUDA_CACHE_MAXSIZE=4294967296"},
	}
	for in, want := range cases {
		if got := withNVIDIAEnv(strings.Fields(in)); fmt.Sprint(got) != fmt.Sprint(want) {
			t.Errorf("%s: got %v, want %v", in, got, want)
		}
	}
}

func TestParseGPUs(t *testing.T) {
	if err := ParseGPUs("all"); err != nil {
		t.Error(err)
	}
	if err := ParseGPUs("0,1"); err == nil || !strings.Contains(err.Error(), "CUDA_VISIBLE_DEVICES") {
		t.Errorf("0,1: %v", err)
	}
}

// As root, the driver shows up in an environment, read-only and with its
// links.
func TestProvideNVIDIA(t *testing.T) {
	if os.Geteuid() != 0 {
		t.Skip("needs root to mount")
	}
	dev, libraries := fakeDriver(t)
	d, err := findNVIDIA(dev, libraries, func(string) (string, error) { return "", errors.New("none") })
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	d.Cache = filepath.Join(t.TempDir(), "cuda")
	t.Cleanup(func() {
		tool.Run("umount", "-R", filepath.Join(root, nvidiaDir))
		for _, device := range d.Devices {
			tool.Run("umount", filepath.Join(root, device))
		}
	})
	if err := provideNVIDIA(root, d); err != nil {
		t.Fatal(err)
	}
	lib := filepath.Join(root, nvidiaDir, "lib64")
	if data, err := os.ReadFile(filepath.Join(lib, "libcuda.so.1")); err != nil || string(data) != "libcuda.so" {
		t.Errorf("libcuda.so.1 reads %q, %v", data, err)
	}
	if err := os.WriteFile(filepath.Join(lib, "libcuda.so.580.95.05"), []byte("x"), 0o755); err == nil {
		t.Error("the host's libcuda is writable from the environment")
	}
	if _, err := os.Stat(filepath.Join(root, dev, "nvidia1")); err != nil {
		t.Errorf("device: %v", err)
	}
	// CUDA's cache outlives the session: it is the host's directory.
	if err := os.WriteFile(filepath.Join(root, nvidiaDir, "cache", "kernel"), []byte("k"), 0o644); err != nil {
		t.Fatal(err)
	}
	if data, err := os.ReadFile(filepath.Join(d.Cache, "kernel")); err != nil || string(data) != "k" {
		t.Errorf("the kept cache has %q, %v", data, err)
	}
}
